# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
#jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
# jekyll-seo-tag > Owners twitter username
author: ADCL # jekyll-seo-tag > default author
# social: # jekyll-seo-tag > social overrides
  # name: ADCL # jekyll-seo-tag > real name
  # links:  # jekyll-seo-tag > social aliases (sameAs)
    # - https://twitter.com/DavidDarnes
    # - https://www.facebook.com/daviddarnes
    # - https://www.linkedin.com/in/daviddarnes
    # - https://github.com/daviddarnes
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Denver # Timezone for blog posts and alike

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
